[theme]
primaryColor = "#4E7FB0"
backgroundColor = "#F8F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2A2A2A"
font = "sans serif"

[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
